export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN_LOGOUT = 'SIGNIN_LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_LOGOUT = 'SIGNUP_LOGOUT';


export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
